# Generated by Django 5.2 on 2025-05-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='weatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('airTemperature', models.CharField(max_length=100, null=True)),
                ('solarRadiance', models.CharField(max_length=100, null=True)),
                ('barometricPressure', models.CharField(max_length=100, null=True)),
                ('lightIntensity', models.CharField(max_length=100, null=True)),
                ('rainfall', models.CharField(max_length=100, null=True)),
                ('relativeHumidity', models.CharField(max_length=100, null=True)),
                ('soilMoisture', models.CharField(max_length=100, null=True)),
                ('soilTemperature', models.CharField(max_length=100, null=True)),
                ('windDirection', models.CharField(max_length=100, null=True)),
                ('windSpeed', models.CharField(max_length=100, null=True)),
                ('bmealtitude', models.CharField(max_length=100, null=True)),
                ('locationLat', models.CharField(max_length=100, null=True)),
                ('locationLong', models.CharField(max_length=100, null=True)),
                ('status', models.BooleanField(null=True)),
            ],
            options={
                'verbose_name_plural': 'weatherData',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='weatherStation',
            fields=[
                ('city_name', models.CharField(max_length=100)),
                ('station_name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
