# Generated by Django 4.2.2 on 2023-06-25 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20220521_0531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weatherdata',
            options={'verbose_name_plural': 'weatherdata'},
        ),
    ]
